version: '3.7'

services:
    db:
     image: mysql:latest
     container_name: letsplay-mysql
     restart: always
     env_file:
       - variables.env
     volumes:
        - ./mysql-data:/var/lib/mysql
        - ./mysql-initdb:/docker-entrypoint-initdb.d
     ports:
       - 3306:3306
     networks:
       - app
       - default
        
    eventapi:
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./EventService/Dockerfile
        env_file:
          - variables.env
        ports:
          - "5103:80"
        networks:
          - app
          #- default  
            
    commentapi:
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./CommentService/CommentService/Dockerfile
        env_file:
          - variables.env
        ports:
          - "5101:80"
        networks:
          - app
          - default  
          
    authapi:
        restart: on-failure
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/letsplay?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true&user=root&password=password
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./AuthService/authservice/Dockerfile
        volumes:
          - /data/authservice
        ports:
          - "8081:8081"
        networks:
          - app
          - default
          
        
volumes:
  mysql-data: 
  mysql-initdb: 
networks:
  app:
    driver: bridge