version: '3.7'

services:
    db:
     image: mysql:latest
     environment:
       MYSQL_DATABASE: letsplay
       MYSQL_USER: root
       MYSQL_PASSWORD: password
       MYSQL_ROOT_PASSWORD: password
     restart: always
     ports:
       - 3306:3306
     volumes:
      - mysql_db_data_container:/var/lib/mysql
      
    phpmyadmin:
      depends_on:
      - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
      - 8080:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password
        
    eventapi:
        depends_on:
        - db
        build:
          context: .
          dockerfile: ./EventService/Dockerfile
        ports: 
            - 5001:80  
            
    commentapi:
        depends_on:
        - db
        build:
          context: .
          dockerfile: ./CommentService/CommentService/Dockerfile
        ports: 
            - 44369:80
volumes:
  mysql_db_data_container: