version: '3.7'

services:
    db:
     image: mysql:latest
     env_file:
       - variables.env
     restart: always
     ports:
       - "3306:3306"
     volumes:
      - mysql_db_data_container:/var/lib/mysql
      
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - "8050:80"
      env_file:
        - variables.env
        
        
    eventapi:
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./EventService/Dockerfile
        env_file:
          - variables.env
        ports:
          - "5103:80"
            
    commentapi:
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./CommentService/CommentService/Dockerfile
        env_file:
          - variables.env
        ports:
          - "5101:80"
    authapi: 
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./AuthService/authservice/Dockerfile
        env_file:
          - variables.env
          
        
volumes:
  mysql_db_data_container:
        