version: '3.7'

services:
    db:
     image: mysql:latest
     container_name: letsplay-mysql
     restart: always
     env_file:
       - variables.env
     volumes:
        - ./mysql-data:/var/lib/mysql
        - ./mysql-initdb:/docker-entrypoint-initdb.d
     ports:
       - 3306:3306         
        
    eventapi:
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./EventService/Dockerfile
        env_file:
          - variables.env
        ports:
          - "5103:80"
            
    commentapi:
        depends_on:
          - db
        build:
          context: .
          dockerfile: ./CommentService/CommentService/Dockerfile
        env_file:
          - variables.env
        ports:
          - "5101:80"
        
volumes:
  mysql-data:
  mysql-initdb: