version: '3'
services:
    eventapi:
        build: .
        context: ./EventService
        ports: 
            - 5001:80    
    commentapi:
        build: .
        context: ./CommentService/CommentService
        ports: 
            - 5002:80      