#docker-compose.override.yml (Extended config for DEVELOPMENT env.)
version: '3.7'

services:
# Simplified number of services here:

  eventapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
     # - ConnectionString=${ESHOP_AZURE_REDIS_BASKET_DB:-eventapi}
     # - identityUrl=http://eventapi
     # - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
    #  - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      #- EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      #- EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      #- AzureServiceBusEnabled=False
      #- ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      #- OrchestratorType=${ORCHESTRATOR_TYPE}
      #- UseLoadTest=${USE_LOADTEST:-False}

    ports:
      - "5103:80"

  commentapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      #- ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word}
     # - PicBaseUrl=${ESHOP_AZURE_STORAGE_CATALOG_URL:-http://localhost:5202/api/v1/catalog/items/[0]/pic/}
     # - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      #- EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      #- EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      #- AzureStorageAccountName=${ESHOP_AZURE_STORAGE_CATALOG_NAME}
      #- AzureStorageAccountKey=${ESHOP_AZURE_STORAGE_CATALOG_KEY}
      #- UseCustomizationData=True
      #- AzureServiceBusEnabled=False
      #- AzureStorageEnabled=False
      #- ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
     # - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5101:80"
