version: '3.7'

services:
    eventapi:
        build:
          context: .
          dockerfile: ./EventService/Dockerfile
        ports: 
            - 5001:80    
    commentapi:
        build:
          context: .
          dockerfile: ./CommentService/CommentService/Dockerfile
        ports: 
            - 5002:80      